### ISSUE TITLE
能不能打包成软件

### ISSUE THREAD

**Issue by tardlk** [Anapopo/fchinanet#1]
原版fchinanet无法查看在线设备数能否添加这个功能然后打包成软件

**Comment by kyya** [comment]
已经支持查看在线设备，打包成软件再考虑。

**Comment by tardlk** [comment]
感谢添加新功能，我是这方面的小白，期待有完整的软件

**Comment by yikexiaoyao** [comment]
怎么用

**Comment by kyya** [comment]
@yikexiaoyao see [README](https://github.com/Anapopo/FChinaNet.js#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)
